[workspace]
authors = ["Fernando Ferraz Ribeiro <ffribeiro@gmail.com>"]
channels = ["conda-forge"]
name = "intro_archicad"
platforms = ["win-64",  "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
srvdoc = "zensical serve"

[dependencies]
python = "3.13.*"
zensical = ">=0.0.31,<0.0.32"
toml = ">=0.10.2,<0.11"

[pypi-dependencies]
gitpython = ">=3.1.46, <4"
